### ISSUE TITLE
New version (2.0.1) you changed your nickname and "Update process" doesn't work anymore

### ISSUE THREAD

**Issue by matxpa** [2009-Nissan-Cube/About-This-Hack#110]
@0xCUB3

Hi
Since you changed your nickname **0xCUB3** by **2009-Nissan-Cube** "Update process" doesn't work anymore 

So you'd have to modify "var **athrepositoryURL** " in **InitGlobalVariables.swift**
...
    // Used by UpdateController
    static var athrepositoryURL        = "https://github.com/0xCUB3/About-This-Hack"
...
replace 0xCUB3 with 2009-Nissan-Cube
    static var athrepositoryURL        = "https://github.com/2009-Nissan-Cube/About-This-Hack"

Regards

**Comment by 0xCUB3** [comment]
It should still work because the old URLs redirect automatically to the new ones.

**Comment by matxpa** [comment]
With your prefered editor (Xcode) try to downgrade CFBundleShortVersionString (from 2.0.1  to 2.0.0 or less) in ATH info.plist in your Applications directory and launch it

		<key>CFBundleShortVersionString</key>
		<string>1.1.9</string>

Regards

**Comment by 0xCUB3** [comment]
you're right. Pushed the change.
