### ISSUE TITLE
About This Hack reads opencore version incorrectly

### ISSUE THREAD

**Issue by PatchedMac** [2009-Nissan-Cube/About-This-Hack#113]
It's not that serious of a issue to be honest, more just a visual thing. 
![Screenshot 2024-09-20 at 12 08 30 AM](https://github.com/user-attachments/assets/f005e630-b026-4bed-8424-e3b648012dda)
ATH seems to not be able to read opencore version correctly now, as version 2 has released this week. I'm sure its a easy fix, but I just wanted to point it out :)

**Comment by 0xCUB3** [comment]
I don't see a problem? OpenCore is being read as it should be.

**Comment by PatchedMac** [comment]
Oh? I thought it was reading the version wrong: 1.0.1 instead of 2.0.1, which is the latest release. If I'm wrong, I'll just close the ticket.
