### ISSUE TITLE
Dual-CPU Macs lack the "2x" note in the Processor line

### ISSUE THREAD

**Issue by FoxRunTime** [2009-Nissan-Cube/About-This-Hack#114]
![Screenshot 2024-10-13 at 13 01 34](https://github.com/user-attachments/assets/a4cc096e-efd7-475c-879c-73127d894a87)

Stock _About This Mac_ makes the user of a machine with two physical CPUs (Mac Pro and Xserve) aware that there are in fact two CPUs. About this Hack does not check for this and simply displays the CPU model, without mention of quantity.

**Comment by 0xCUB3** [comment]
oh dear. yeah I should probably implement this. Dual-CPU users are a small minority so it never occurred to me.

**Comment by FoxRunTime** [comment]
I am more than happy to test on my machine if/when you choose to implement this :)

**Comment by 0xCUB3** [comment]
Fixed with #119
