### ISSUE TITLE
No translucency on 'Displays' tab macOS Sequoia

### ISSUE THREAD

**Issue by 2003FordFocus** [2009-Nissan-Cube/About-This-Hack#117]

**Comment by 2003FordFocus** [comment]
usually, about this Hack has a translucent background. It does on the Overview, Storage, and Support tabs. Displays does not have a translucent background. Nothing wrong, it's just an aesthetic thing that needs changing

**Comment by 0xCUB3** [comment]
I think the issue might just be that I need to compile the app with the latest version of Xcode. When I have some time I'll fix this along with the other bugs present. 

Love the username btw.

**Comment by 2003FordFocus** [comment]
Thanks - no rush, just would like to see it at some point in the future

**Comment by 2003FordFocus** [comment]
Fixed now as of latest macOS update 👍

**Comment by 0xCUB3** [comment]
I also just changed the code so translucency is fixed on all versions :)

**Comment by SmexyGorilla** [comment]
Thank you 😊
